## For more information on this config, please see https://docs.netlify.com/routing/redirects
[[redirects]]
  from = "/posts/:splat"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/how-to-add-open-source-software-projects-to-sourcegraph"
  to = "/how-to-add-open-source-software-projects-to-sourcegraph-cloud"
  status = 301
  force = true

[[redirects]]
  from = "/sourcegraph-cheat-sheet"
  to = "/how-to-search-code-with-sourcegraph-a-cheat-sheet"
  status = 301
  force = true

[[redirects]]
  from = "/literal-search-patterns"
  to = "/how-to-search-code-with-sourcegraph-using-literal-patterns"
  status = 301
  force = true

[[redirects]]
  from = "/regular-expression-patterns"
  to = "/how-to-search-with-sourcegraph-using-regular-expression-patterns"
  status = 301
  force = true

[[redirects]]
  from = "/structural-search-patterns"
  to = "/how-to-search-with-sourcegraph-using-structural-patterns"
  status = 301
  force = true

[[redirects]]
  from = "/three-ways-to-search-video"
  to = "/three-ways-to-search-code-with-sourcegraph"
  status = 301
  force = true

[build]
  command="NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL npm run build"
  publish="out"

## Non-sensitive env vars
[context.production]
  command="NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL npm run build"
  [context.production.environment]
    NEXT_PUBLIC_URL="https://learn.sourcegraph.com"
    NEXT_PUBLIC_GTM_ID="GTM-TB4NLS7"
[context.deploy-preview]
  command="NEXT_PUBLIC_URL=$DEPLOY_URL npm run build"
  [context.deploy-preview.environment]
    NEXT_PUBLIC_URL="$DEPLOY_URL"
    NEXT_PUBLIC_GTM_ID="GTM-TB4NLS7"
    NEXT_PLUGIN_FORCE_RUN="false"