## For more information on this config, please see https://docs.netlify.com/routing/redirects
[[redirects]]
  from = "/posts/*"
  to = "/:splat"
  status = 301
  force = true
[context.production]
  [context.production.environment]
    NEXT_PUBLIC_URL="https://learn.sourcegraph.com"
[context.deploy-preview]
  [context.deploy-preview.environment]
    NEXT_PUBLIC_URL="$DEPLOY_URL"