## For more information on this config, please see https://docs.netlify.com/routing/redirects
[[redirects]]
  from = "/posts/*"
  to = "/:splat"
  status = 301
  force = true

[build]
  command="NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL npm run build"

## Non-sensitive env vars
[context.production]
  command="NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL npm run build"
  [context.production.environment]
    NEXT_PUBLIC_URL="https://learn.sourcegraph.com"
    NEXT_PUBLIC_GTM_ID="GTM-TB4NLS7"
[context.deploy-preview]
  command="NEXT_PUBLIC_URL=$DEPLOY_URL npm run build"
  [context.deploy-preview.environment]
    NEXT_PUBLIC_URL="$DEPLOY_URL"
    NEXT_PUBLIC_GTM_ID="GTM-TB4NLS7"